apiVersion: performance.openshift.io/v1alpha1
kind: PerformanceProfile
metadata:
  name: worker-cnf-2
spec:
  additionalKernelArgs:
    - nmi_watchdog=0
    - audit=0
    - mce=off
    - processor.max_cstate=1
    - idle=poll
    - intel_idle.max_cstate=0
    - nosmt
    - tsc=reliable
  cpu:
    isolated: 2-103
    reserved: 0-1
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
    - size: "1G"
      count: 16
      node: 0
  numa:
    topologyPolicy: best-effort
  realTimeKernel:
    enabled: true
  nodeSelector:
    node-role.kubernetes.io/worker-cnf-2: ""
