apiVersion: performance.openshift.io/v1
kind: PerformanceProfile
metadata:
  name: worker-cnf
spec:
  additionalKernelArgs:
    - nosmt
  cpu:
    isolated: 2-39
    reserved: 0-1
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
    - size: "1G"
      count: 16
      node: 0
  numa:
    topologyPolicy: best-effort
  realTimeKernel:
    enabled: true
  nodeSelector:
    node-role.kubernetes.io/worker-cnf: ""
