apiVersion: v1
kind: Pod
metadata:
  name: sriovpod
  namespace: sriov-testing
  annotations:
    k8s.v1.cni.cncf.io/networks:  sriov-network
spec:
  containers:
  - name: sriovpod
    command: ["/bin/sh", "-c", "trap : TERM INT; sleep 600000& wait"]
    image: alpine
